config/routes.rb
Cs2::Application.routes.draw do

  # static pages
  match "/home" => "pages#home"
  match "/contact" => "pages#contact"
  match "/about" => "pages#about"
  match "/outline" => "pages#outline"
  match "/testimonials" => "pages#testimonials"
  match "/payment" => "pages#payment"

  root :to => "pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About course"
  end

  def outline
    @title = "Course outline"
  end

  def testimonials
    @title = "Testimonials"
  end

  def payment
    @title = "Payment"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>USMLE Step 2 CS Coaching | <%= @title %></title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="everything-but-footer">
      <header>
        <h1>USMLE Step 2 CS Coaching</h1>
      </header>
      <div class="nav_content">
        <nav>
          <ul>
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About course", about_path %></li>
            <li><%= link_to "Course outline", outline_path %></li>
            <li><%= link_to "Testimonials", testimonials_path %></li>
            <li><%= link_to "Contacts", contact_path %></li>
            <li><%= link_to "Payment", payment_path %></li>
          </ul>
        </nav>
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>
    <footer>
      <hr/>
      <p>© Copyright Armin Moradi 2011-2012</p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h3><%= @title %></h3>
<p>The sessions are offered on a per-hour basis.  Discounted packages are also offered as mentioned below:</p>
<br />
<p>per-hour sessions: $35/hr with flexible schedule.</p>
<p>9 session package: $335: includes 9 sessions and covers a total of 35 cases.</p>
<p>6 session package: $235: includes 6 sessions and covers a total of 25 cases.</p>
<br />
<p>Please note that sessions are taught through Skype™ only.</p>
<br />
<p>The sessions include all of the High Yield and UW cases.  Some important cases not covered by these sources are also emphasized which are necessary to be practiced.</p>

app/views/pages/contact.html.erb
<h3>Contact information</h3>
<p>You can contact me either through email or Skype.</p>
<br />
<br />

<hr class="section-hr" />
<p>Email:</p>
<%= mail_to "coach@sajdahcs2coaching.com" %></p>
<br />
<br />

<hr class="section-hr" />
<p>Skype (id: md_cs2):</p>
<!-- Skype 'Skype Me!' button http://www.skype.com/go/skypebuttons -->
<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
<form><input type="button" value="Call me" onclick="window.location.href='skype:md_cs2?call'" /></form>
<%# <a href="skype:md_cs2?call"><img src="http://download.skype.com/share/skypebuttons/buttons/call_blue_white_124x52.png" style="border: none;" width="124" height="52" alt="Skype Me™!" /></a> %>

app/views/pages/home.html.erb
<h3><%= @title %></h3>
<p>Highly experienced tutor and coach for USMLE Step 2 Clinical Skills test.  If you want to pass the USMLE Step 2 CS exam on the first attempt, do not hesitate to join my CS 2 coaching classes.</p>
<br />
<p>The sessions are guaranteed to prepare you well for the ultimate clinical skills test.  You will see a big improvement in how you handle the test after the first session of my demonstration.</p>
<br />
<p>I have been coaching Step 2 CS since 2008 and 98% of my students have passed on the first attempt.</p>

app/views/pages/outline.html.erb
<h3><%= @title %></h3>

<!-- Outline of the course -->
<p>This course is taught exactly according to the ECFMG recommendation given on <a href="http://www.ecfmg.org">ecfmg.org</a>.  The patient encounter is subdivided into multiple sections and each section is covered in detail.  Please note that I emphasize and focus on the sensitive and score-gaining and also potentially exam-failing areas.  The following gives a brief outline of the material/skills covered during the sessions:</p>
<p></p>
<br />
<ul class="outline">
  <li>Professional introduction</li>
  <li>Asking questions during hand-washing</li>
  <li>
    History taking
    <ul class="sub-outline">
      <li>covers C.I.S.</li>
      <li>Professional data gathering (I.C.E.) skills</li>
    </ul>
  </li>
  <li>Handling an uncooperative patient</li>
  <li>Understanding triggers for empathy</li>
  <li>Professional question-asking techniques</li>
  <li>Information sharing</li>
  <li>Closure</li>
  <li>Counseling
    <li>A crucial part of the encounter for passing the Step 2 CS</li></li>
  <li>Patient note</li>
</ul>
<br />
<br />

<!-- Tips section -->
<hr class="section-hr" />
<p>Here are a few tips to help you get started thinking about proper encounter techniques:</p>
<br />
<ul class="outline">
  <li>
    Never use medical jargon
    <ul class="sub-outline">
      <li>Never ask a patient whether he/she has had a colonoscopy</li>
    </ul>
  </li>
  <li>If you have repeated a question by mistake, apologize and mention that you only wanted to clarify</li>
  <li>When starting to ask about past medical history, use a transitioning sentence</li>
  <li>When opening sub-history, ask the patient whether he/she has had the same complaint before</li>
  <li>If the complaint runs in the family, show care and empathy and then elaborate on it</li>
  <li>Be focused at all time: use the allocated time wisely and efficiently</li>
</ul>
<br />
<br />

<!-- Closure -->
<hr class="section-hr" />
<p>And the following deals with the closure section of the encounter:</p>
<br />
<ul class="outline">
  <li>Summarizing findings about the patient</li>
  <li>Displaying differetials</li>
  <li>Work-up plan</li>
  <li>What not to say during closure</li>
  <li>Counseling the patient if required</li>
  <li>Professionally closing the encounter</li>
</ul>
<br />
<br />

<!-- Counseling -->
<hr class="section-hr" />
<p>The following are only a few of many counseling points covered in the sessions:</p>
<br />
<ul class="outline">
  <li>Adult
    <li>Smoking</li>
    <li>Safe sexual practice</li>
    <li>Depression</li>
    <li>Insomnia</li>
    <li>Weight gain/loss</li>
    <li>Drinking problems</li> 
  </li>

  <li>Pediactric
    <li>Picky eater</li>
    <li>Bed wetting</li>
    <li>Fever</li>
    <li>Diarrhea</li>
  </li>
</ul>
<br />
<br />

app/views/pages/testimonials.html.erb
<h3><%= @title %></h3>
<p>From Ko Ko T</p>
<p>I'd like to thank you for the practice sessions. I got my CS exam results a few days ago. You were right about recommending me to take a few days off from work to practice intensively. That helped me a lot in passing the exam.</p>
<br /><br />

<hr class="section-hr" />
<p>From ShweYee:</p>
<p>Hi Farat, i got the result,, i pass</p>
<br />
<br />

<hr class="section-hr" />
<p>From Pooja S:</p>
<p>I got my cs result and i passed my exam.Thank u for ur help and guidance for me</p>
<br />
<br />

<hr class="section-hr" />
<p>From Aisha N:</p>
<p>I just have to share some good news with you. I received my CS result yesterday and ... Passed it!!!<br />
Farah I would like to take this opportunity to thank you for all your time and patience with me. You taught me everything I know from the basics to the patient note.<br />
Also, thank you for believing in me... Even when I didn't. You were so confident and sure that I would pass.. That gave me so much strength. I would just close my eyes and think about you. I know u gave me so much extra time and I'm very grateful for each and every minute. From the bottom of my heart, thank you for everything.<br />
I would like to ask you- if you still tutor students for CS, I can vouch and give a good recommendation to other students... Via email or skype even. Please let me know if I can be of any assistance to you.<br />
Farah, thank you is a very small word for what you did for me.. But that's all I can say to you. Im thankful our paths crossed and we came in contact.. U my friend and my sister shall always have a special place in my heart as well as my prayers.<br />
</p>
<br />
<br />

<hr class="section-hr" />
<p>From Shiva:</p>
<p>I really really want to thank you for your help, wish you the best and wish I could do something in return...<br />
yours, Shiva</p>